# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e51d1092f98e1a0a710d1cd764d1cd6b511ee4b1332cb5f3d07c054692f526573b732f2330a18eeed1212fd3825e065568fdce55c224a693fd2e95c9153569a

test:
  secret_key_base: 6d948feae44bc1e6ec4f5259a165f188a2b2e3883311ee75c1eb81068e4088c65ca6ade2d8c15363c3c600e6a26e8f82ae8b19433db703967bf9cf430473bee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
